import type { Metadata } from 'next';
import { Nunito_Sans, Geist } from 'next/font/google';
import './globals.css';
import { QueryProvider } from './queryProvider';

// Default font
const nunitoSans = Nunito_Sans({
  variable: '--font-nunito_sans',
  weight: '400',
  subsets: ['latin'],
});

// Additional font
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} ${geistSans.variable} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
